import logo from "./logo.png";
import authbg from "./auth-bg.png";
import video from "./video.png";
import teamLogo from "./team-logo.png";
import graph from "./graph.png";
import arrowdown from "./arrowdown.png";
import illustration1 from "./Illustration-1.png";
import illustration2 from "./Illustration-2.png";
import feature1 from "./feature1.png";
export { logo, authbg, video, teamLogo, graph, arrowdown, illustration1, illustration2, feature1 };
